# Generated by Django 3.2.4 on 2021-06-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
    ]
