# Generated by Django 3.2.4 on 2021-06-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.CharField(default=132, max_length=100),
            preserve_default=False,
        ),
    ]
