# Generated by Django 3.2.4 on 2021-06-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210622_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=7),
            preserve_default=False,
        ),
    ]
